### PR TITLE
Add DocumentDB support

### PR DESCRIPTION
**Pull request by cdvieu**
Issue #222 

Description of changes:
Adding functionality to support the scheduling of DocDB resources. Updated rds_service to exclude DocDB resources as DocDB was implicitly included due to overlapping API calls.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by maykays** [comment]
Thank you for the PR. We are unable to support this PR at the moment based on a scaling concern. We are working towards a solution for Q3/4 2021.

**Comment by brianmjones** [comment]
@maykays I have a few questions. What is the scaling concern? Is the scaling concern with the existing codebase or with our code? Are you expecting us to do another PR when the scaling concern is addressed?

**Comment by gockle** [comment]
Hi @brianmjones Scaling concerns are with the solution itself, the current design of instance scheduler solution has some limitation which needs to be addressed, we are currently evaluating a new other design options for the solution, Hence at this point we don't want to include/expand this solution in its current architecture to more service. The PR looks good technically no more changes are required from your end. Let me know if you have any further questions.

**Comment by cdvieu** [comment]
Is the solution for the scaling concerns still scheduled to happen in Q3/Q4? We're looking for an update for planning purposes. Thanks!

**Pull request closed without merging**
